GET http://localhost:8000/api/users?page=1 HTTP/1.1

###
GET http://localhost:8000/api/users/3 HTTP/1.1

###

POST http://localhost:8000/api/users HTTP/1.1
Content-Type: application/json

{
    "lastname": "mbele",
    "firstname":"valery",
    "email":"gamer@test.com",
    "roleId":1
}

###

PUT http://localhost:8000/api/users/7 HTTP/1.1
Content-Type: application/json

{
    "lastname": "mbeleval",
    "firstname":"valou",
    "roleId":3
}
###

DELETE http://localhost:8000/api/users/18 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/api/users/info HTTP/1.1
Content-Type: application/json

{
    "lastname": "mebel"
}
###

PUT http://localhost:8000/api/users/password HTTP/1.1
Content-Type: application/json

{
    "password": "valery54",
    "passwordConfirm": "valery54"
}
###

